redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

development: *redis

#test:
#  adapter: redis
#  url: redis://localhost:6379/test

#production:
#  adapter: redis
#  url: <%#= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#  channel_prefix: AskAns_production
