default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: AskAns_development
  username: professor
  password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: AskAns_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
